version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Build
          command: npm run build:prod
      - run:
          name: Run Unit Tests
          command: npm run test
